sudo: required
dist: trusty
language: c
compiler:
  - gcc
# Change this to your needs
before_install:
  - sudo add-apt-repository ppa:cryptotronix/ppa  -y
  - sudo apt-get update -q
  - sudo apt-get install yacl-dev libssl-dev pkg-config -y

script: ./autogen.sh
